### ISSUE TITLE
整合 sprintboot dataway , 启动成功访问/interface-ui/失败

### ISSUE THREAD

**Issue by lgw8186** [zycgit/hasor#11]
整合 sprintboot dataway , 启动成功了，但是访问/interface-ui/报错
let.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-04-21 00:47:57.320  INFO 47720 --- [nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 12 ms
2020-04-21 00:47:57.358 ERROR 47720 --- [nio-8081-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.lang.NullPointerException: null
	at net.hasor.utils.io.IOUtils.copyLarge(IOUtils.java:1556) ~[hasor-commons-4.1.3.jar:na]
	at net.hasor.utils.io.IOUtils.copyLarge(IOUtils.java:1535) ~[hasor-commons-4.1.3.jar:na]
	at net.hasor.utils.io.IOUtils.copy(IOUtils.java:1512) ~[hasor-commons-4.1.3.jar:na]
	at net.hasor.dataway.config.InterfaceUiFilter.doInvoke(InterfaceUiFilter.java:91) ~[hasor-dataway-4.1.3.jar:na]
	at net.hasor.web.binder.FilterDef.doInvoke(FilterDef.java:99) ~[hasor-web-4.1.3.jar:na]
	at net.hasor.web.invoker.InvokerChainInvocation.doNext(InvokerChainInvocation.java:41) ~[hasor-web-4.1.3.jar:na]
	at net.hasor.web.invoker.InvokerChainInvocation.doNext(InvokerChainInvocation.java:43) ~[hasor-web-4.1.3.jar:na]
	at net.hasor.dataql.fx.web.FxWebInterceptor.doInvoke(FxWebInterceptor.java:40) ~[hasor-dataql-fx-4.1.3.jar:na]
	at net.hasor.web.binder.FilterDef.doInvoke(FilterDef.java:99) ~[hasor-web-4.1.3.jar:na]
	at net.hasor.web.invoker.InvokerChainInvocation.doNext(InvokerChainInvocation.java:41) ~[hasor-web-4.1.3.jar:na]
	at net.hasor.web.render.RenderWebPlugin.doRenderInvoker(RenderWebPlugin.java:124) ~[hasor-web-4.1.3.jar:na]
	at net.hasor.web.render.RenderWebPlugin.doInvoke(RenderWebPlugin.java:80) ~[hasor-web-4.1.3.jar:na]
	at net.hasor.web.binder.FilterDef.doInvoke(FilterDef.java:99) ~[hasor-web-4.1.3.jar:na]
	at net.hasor.web.invoker.InvokerChainInvocation.doNext(InvokerChainInvocation.java:41) ~[hasor-web-4.1.3.jar:na]
	at net.hasor.web.invoker.InvokerContext.lambda$genCaller$3(InvokerContext.java:106) ~[hasor-web-4.1.3.jar:na]

<hasor.version>4.1.3</hasor.version>
<dataway.version>4.1.3</dataway.version>
jdk1.8

**Comment by zycgit** [comment]
dateway 4.1.3 版本资源文件缺失问题，重新拉取一下版本替换


<dependency>
<groupId>net.hasor</groupId>
<artifactId>hasor-dataway</artifactId>
<version>4.1.3-fix20200414</version>
</dependency>
