### ISSUE TITLE
Unknown SqlMode.

### ISSUE THREAD

**Issue by xxmfypp** [zycgit/hasor#20]
运行示例报下面的错误，啥原因？
2020-04-29 17:29:51.341  INFO 17824 --- [           main] com.xxmfypp.test.HasorApplication        : Started HasorApplication in 1.8 seconds (JVM running for 2.445)
2020-04-29 17:29:52.835  INFO 17824 --- [nio-8111-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-04-29 17:29:52.835  INFO 17824 --- [nio-8111-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-04-29 17:29:52.846  INFO 17824 --- [nio-8111-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 11 ms
2020-04-29 17:29:53.082 ERROR 17824 --- [nio-8111-exec-1] net.hasor.dataway.web.PerformController  : Unknown SqlMode.

net.hasor.dataql.runtime.InstructRuntimeException: Unknown SqlMode.
	at net.hasor.dataql.runtime.mem.RefCall.lambda$invokeMethod$0(RefCall.java:60) ~[hasor-dataql-4.1.3.jar:na]
	at net.hasor.utils.ExceptionUtils.toRuntimeException(ExceptionUtils.java:40) ~[hasor-commons-4.1.3.jar:na]
	at net.hasor.dataql.runtime.mem.RefCall.invokeMethod(RefCall.java:60) ~[hasor-dataql-4.1.3.jar:na]
	at net.hasor.dataql.runtime.inset.CALL.doWork(CALL.java:58) ~[hasor-dataql-4.1.3.jar:na]
	at net.hasor.dataql.runtime.inset.OpcodesPool.doWork(OpcodesPool.java:42) ~[hasor-dataql-4.1.3.jar:na]
	at net.hasor.dataql.runtime.mem.RefLambdaCall.call(RefLambdaCall.java:53) ~[hasor-dataql-4.1.3.jar:na]

**Comment by xxmfypp** [comment]
数据库为MySql5.7 Jar 的版本如下： 
<dependency>
            <groupId>net.hasor</groupId>
            <artifactId>hasor-spring</artifactId>
            <version>4.1.3</version>
        </dependency>
        <dependency>
            <groupId>net.hasor</groupId>
            <artifactId>hasor-dataway</artifactId>
            <version>4.1.3-fix20200414</version>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.39</version>
        </dependency>
