### ISSUE TITLE
setupEnvironment 报NPE  

### ISSUE THREAD

**Issue by BeginMan** [zycgit/hasor#80]
集成其他spring框架时如果环境变量值为null就报错

**报错信息：**
```java
Caused by: java.lang.NullPointerException: null
	at java.util.Hashtable.put(Hashtable.java:460)
	at java.util.Hashtable.putAll(Hashtable.java:524)
	at net.hasor.spring.beans.AbstractEnvironmentAware.setupEnvironment(AbstractEnvironmentAware.java:47)
	at net.hasor.spring.beans.AbstractTypeSupplierTools.setEnvironment(AbstractTypeSupplierTools.java:47)
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:105)
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:96)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:413)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1761)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	... 85 common frames omitted
```

**问题定位：**
AbstractEnvironmentAware类setupEnvironment方法， 对于`propertySource.getSource()` 如果map中value有null 则，`putAll` 报NEP。

```java
// AbstractEnvironmentAware.setupEnvironment

if (source instanceof Map) {
    envProperties.putAll(((Map) source));
}
```

**其他信息**：

版本：4.1.9

**Comment by zycgit** [comment]
确认有 NPE 问题，net.hasor:hasor-spring:4.1.9-fix20201201 提供了对应版本的临时解决方案。

并且合入尚在开发的 4.2.2 分支
